### ISSUE TITLE
Checklist of things to fix:

### ISSUE THREAD

**Issue by marimeireles** [wireless-hippie/wireless-hippie.github.io#1]
- [x] gravatar id
- [x] create a logo
- [x] create a favicon
- [x] make the tag explorer waaay smaller
- [x] maybe posts should occupy a whole role instead of 6/6
- [x] fix the upper bar removing weird links
- [x] remove the author box in each post, there can BE ONLY ONE
- [x] fix mailchimp-list
- [x] fix description on _config
